#!/bin/sh

# This hook adds the JIRA ticket ID from branch name to every commit.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

case "$COMMIT_SOURCE,$SHA1" in
  ,|template,)
    /usr/bin/perl -i.bak -pe '
       print "\n" . `git diff --cached --name-status -r`
     if /^#/ && $first++ == 0' "$COMMIT_MSG_FILE" ;;
  *) ;;
esac

# get current branch
branchName=`git rev-parse --abbrev-ref HEAD`
branchName_uc=$(echo $branchName | tr '[:lower:]' '[:upper:]')

# search JIRA issue id in a pattern such a "feature/ABC-123-description"
jiraId=$(echo $branchName_uc | /usr/bin/perl -ne '/[^\/]*\/([a-zA-Z]+-[0-9]+)/ && print $1')

# only prepare commit message if pattern matched and jiraId was found
if [ -n "$jiraId" ]; then
  matches=$(head -n1 "$COMMIT_MSG_FILE" | grep -c "\[$jiraId\]")

  # only add the jira ticket, if it is not already there.
  if [ "$matches" = "0" ]; then # textual match, because numeric "error string" -eq 0 is true

    sed -i.bak -e "1s/^/\[$jiraId\] /" "$COMMIT_MSG_FILE"
  fi
fi
