version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/Los_Angeles"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    allow:
      - dependency-type: direct
    reviewers:
      - gametimesf/eng-backend
    labels:
      - "Needs 1 review"
