description: |
  Braintree-go is a third-party client for Braintree APIs

contact: tribe-payments@hellofresh.com
known-name: braintree-go
squad: payments-platform
tribe: payments
concourse-team: payments.payments-platform
slack-channel: "#tribe-payments"
labels:
- payments
public_urls: []
private_urls: []
docs:
- https://github.com/hellofresh/braintree-go
