package main

import (
	"fmt"
	"html/template"
	"log"
	"net/http"

	"github.com/lionelbarrow/braintree-go"
)

func main() {
	bt := braintree.New(
		braintree.Sandbox,  // We're testing, so this is the env
		"<YourMechID>",     // Mech ID
		"<YourPublicKey>",  // Public Key
		"<YourPrivateKey>", // Private key
	)

	// Basic serving of payment form
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// We generate a clientToken for the client side JS
		clientToken, err := bt.ClientToken().Generate()
		if err != nil {
			log.Fatal(err)
		}
		// Create a template.
		t := template.New("form.html")
		// Parse the template file.
		t, _ = t.ParseFiles("form.html")
		w.WriteHeader(http.StatusOK)
		err = t.Execute(w, clientToken)
		if err != nil {
			log.Fatal(err)
		}
	})

	// Handle the checkout
	http.HandleFunc("/checkout", func(w http.ResponseWriter, r *http.Request) {
		// paymentMethodNonce is generated at client side by the Braintree JS
		paymentMethodNonce := r.PostFormValue("payment_method_nonce")
		if paymentMethodNonce == "" {
			log.Fatal("Payment method nonce is empty")
		}
		// You can later search for the user by his ID
		// customer, err := bt.Customer().Find("CustomerID")
		customer, err := bt.Customer().Create(&braintree.Customer{
			// You can leave it empty, but, if you've got a user system, I recommend using the user's ID as the client ID
			// Or, createa a row for Braintree's customer ID
			Id: "<CustomerID>",
		})
		if err != nil {
			log.Fatal(err)
		}

		// We create a credit card that after generation, gives us the PaymentMethodToken that's needed in the Subscription.Create
		card, err := bt.CreditCard().Create(&braintree.CreditCard{
			// The created or existing customer ID
			CustomerId: customer.Id,
			// The nonce from the clinet side
			PaymentMethodNonce: paymentMethodNonce,
			Options: &braintree.CreditCardOptions{
				VerifyCard: true,
			},
		})
		if err != nil {
			log.Fatal(err)
		}

		// Create the subscription and make the user pay
		subscription, err := bt.Subscription().Create(&braintree.Subscription{
			PlanId: "<YourPlanIDShouldGoHere>",
			// The payment method token generated by the CreditCard.Create
			PaymentMethodToken: card.Token,
		})
		if err != nil {
			log.Fatal(err)
		}

		// Hooray!
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(fmt.Sprintf("Success! Subscription #%s created with user ID %s", subscription.Id, customer.Id)))
	})
	http.ListenAndServe(":8080", nil)

}
