on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
name: pr checks
jobs:
  go-checks:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/gametimesf
      IS_GITHUB: true
    steps:
      - name: Configure git for private modules
        env:
          ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: git config --global url."https://$ORG_GITHUB_TOKEN@github.com/gametimesf".insteadOf "https://github.com/gametimesf"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: gofmt
        uses: gametimesf/github-actions/go/fmt@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: gomodcheck
        uses: gametimesf/github-actions/go/gomodcheck@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # this token needs access to all repos in the org
          ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
          
